### ISSUE TITLE
Revoir la conception de la page "démarche" -> Les projets

### ISSUE THREAD

**Issue by bouviermullerp** [data-players/prats-enr-platform#13]
https://prats-enr.data-players.com/Page/demarche/show

Elle affiche un fil d'Ariane qui permet d'atterir sur "page" (ça serait mieux si c'était caché)

La page démarche s'appelle en fait "projet" sur le figma et elle affiche le même texte que sur l'a page d'accueil https://prats-enr.data-players.com/Page/demarche/show

**Comment by simonLouvet** [comment]
les contenus es 2 pages sont différenciés pour pouvoir avoir un résumé en page d’accueil

**Comment by simonLouvet** [comment]
Besoin de spécifier quel doit être le fil d’Ariane @bouviermullerp pour l'affichage des écrans "page/.../show"
